apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: rakshithcg/rakshithg:latest
        imagePullPolicy: Always
        name: k8s-ct
        containerPorts:
        - port: 8080
